### ISSUE TITLE
Add Quantuam Efficiency to galcheat

### ISSUE THREAD

**Issue by ismael-mendoza** [aboucaud/galcheat#106]
As discussed in the meeting yesterday, we so far have been assuming its 1 so electron = photons = photoelectrons. If not we can at least state this assumption explicitly in the documentation, etc.

**Comment by aboucaud** [comment]
I thought the end of the discussion was that QE is taken into account in the zeropoint computation from `speclite`(cc @mpaillassa) which end up computing a reference for 1 e-/second. 
Since magnitudes are always computed relative to the band zeropoint, the prescription 1 photon = 1 e- is verified and is not just an assumption.

Do you agree @mpaillassa, @herjy ?

**Comment by mpaillassa** [comment]
Yes I agree !

**Comment by ismael-mendoza** [comment]
Yes that sounds good @aboucaud, in that case you can close this PR I think ?

**Comment by aboucaud** [comment]
Settled for now
