### ISSUE TITLE
Change name in HST.yaml from HST_COSMOS to HST

### ISSUE THREAD

**Issue by ismael-mendoza** [aboucaud/galcheat#83]
or change the file name to `HST_COSMOS.yaml`. The inconsistency is causing some errors when I try to use it.

**Comment by aboucaud** [comment]
Good catch.

Then just as we switched Rubin to LSST, we may want to switch from HST to COSMOS directly.
The survey is COSMOS, right ?

**Comment by ismael-mendoza** [comment]
Yup  I believe you are right

**Comment by mpaillassa** [comment]
I agree that we should not let HST as it is not the survey name but COSMOS alone could be a bit confusing as it also refers to the name of the corresponding area in the sky in a general way, and it has been observed in many other surveys where it is also referred as COSMOS. In the [COSMOS website](https://cosmos.astro.caltech.edu/page/astronomers), they present it like a field observed by many surveys. So we may name it COSMOS_HST or even COSMOS_HST_ACS because the field has been observed with other instruments than ACS embedded with HST... But I admit that it is a bit heavy...

**Comment by mpaillassa** [comment]
As I just wondered for Euclid in #87, this is a similar case where a survey (COSMOS) has several instruments and our way to deal with this is to mention the instrument, hence Euclid_VIS for Euclid, as mentioned in the [README](https://github.com/aboucaud/galcheat/blob/main/galcheat/data/README.md).
But here there is one more level because it consists of an instrument of an instrument (the ACS camera of HST). So I do not know if we should go for COSMOS_HST, COSMOS_ACS or COSMOS_HST_ACS...

**Comment by mpaillassa** [comment]
Reopening @aboucaud @ismael-mendoza

**Comment by aboucaud** [comment]
Good point.

These projects have not decided to make our lives easy..

**Comment by mpaillassa** [comment]
I think it could be clearer to reason with surveys and survey fields as "sub-surveys". For instance, `HSC` is a survey, but it consists of different survey fields (wide, deep, ultradeep, etc) which can be seen as sub-surveys. The "instrument" parameters do not depend on the sub-surveys but some filter parameters such as `exposure_time` or `psf_fwhm` do depend on which sub-survey we are considering. For `HSC`, we implicitly made the assumption that it was `HSC_wide` in galcheat by setting `exposure_time` and `psf_fwhm` to the wide field measurements. But if one wants to simulate HSC deep observations, one has to define another `HSC` survey. 

So I don't know what we should do in galcheat. Either we let the general survey names and have implicit survey fields like now, either we decide that we need to somehow indicate the survey field. 

To avoid confusions and for clarity I would say that we should somehow indicate the survey field. To do that I would propose having a `field_name` parameter to avoid renaming surveys... In that case we would have:
* CFHTLS: wide
* DES: wide
* Euclid_VIS: wide
* HSC: wide
* LSST: lsst (?)

Coming back to the `COSMOS` case, the thing is that the survey and the survey field are both COSMOS. So it would have `name: "COSMOS"` and `field_name: "cosmos"`. The only thing that is a bit unsatisfying is that it does not make the instrument name (HST ACS) appearing because unlike all other surveys, it is not part of the survey name.

**Comment by mpaillassa** [comment]
Yes it's true that having a field attribute is not working if we would like to keep the same survey name... So it's either incorporating the field name in the survey name or keeping it implicit like now. And I agree that it seems reasonable to assume that most users will think of the wide-field surveys by default. 

In the same spirit it also seems reasonable to assume that most users will think of the HSC ACS observations for the `COSMOS` survey (which was the initial issue :smile: )

And I agree to have a `description` parameter !
